### ISSUE TITLE
fatal error: all goroutines are asleep - deadlock!

### ISSUE THREAD

**Issue by jmnote** [kuoss/ingress-annotator#18]
```
&{{ 0     [0x19568c0] <nil>} map[] {{{} 0} {0 0}} false {0 0} <nil>}
fatal error: all goroutines are asleep - deadlock!
goroutine 1 [select]:
sigs.k8s.io/controller-runtime/pkg/cache/internal.(*Informers).waitForStarted(...)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/cache/internal/informers.go:244
sigs.k8s.io/controller-runtime/pkg/cache/internal.(*Informers).WaitForCacheSync(0xc00057d400, {0x20cc208, 0x30fa8e0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/cache/internal/informers.go:274 +0x76
main.run({0x20dfc60, 0xc0003ff1e0})
	/workspace/cmd/main.go:126 +0x4d
main.main()
	/workspace/cmd/main.go:62 +0xfb
```

**Comment by jmnote** [comment]
WaitForCacheSync
